### ISSUE TITLE
Fluxgui doesn't run on Opensuse Leap 15

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [xflux-gui/fluxgui#101]
I compiled the application but it doesn't load.

When I try to run it from terminal, I get this error :

> Traceback (most recent call last):
>   File "/usr/bin/fluxgui", line 17, in <module>
>     from fluxgui.fluxapp import main
>   File "/home/ahmed/.local/lib/python2.7/site-packages/fluxgui/fluxapp.py", line 3, in <module>
>     from fluxgui import fluxcontroller, settings
>   File "/home/ahmed/.local/lib/python2.7/site-packages/fluxgui/fluxcontroller.py", line 1, in <module>
>     from fluxgui import xfluxcontroller
>   File "/home/ahmed/.local/lib/python2.7/site-packages/fluxgui/xfluxcontroller.py", line 5, in <module>
>     from fluxgui import settings
>   File "/home/ahmed/.local/lib/python2.7/site-packages/fluxgui/settings.py", line 2, in <module>
>     import gconf
> ImportError: No module named gconf

**Comment by jhlav** [comment]
@ahmed-elsayed2017 I had this issue as well.  I fixed it by installing [this package, python-gconf](https://software.opensuse.org/package/python-gconf).  There is only a community-compiled version for Leap 15 right now, but it works.

On the page for the above link, click **Show Community Packages** under **openSUSE Leap 15.0** and you can click to install with YaST.  Otherwise, you could go to that package's page and add the repo to install manually with zypper.

![image](https://user-images.githubusercontent.com/20038091/45530183-64a17080-b7b7-11e8-9090-0fb228edaf2f.png)

**Comment by ahmed-elsayed2017** [comment]
Ok. Thanks.
