### ISSUE TITLE
Doesn't work on Ubutnu 18.04

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [xflux-gui/fluxgui#102]
I can install it and run it successfully, but it does not work.

I tried to compile it manually, but when I try to run it in terminal, it gives me this error :

Gtk-Message: 02:52:44.841: Failed to load module "canberra-gtk-module"

**Comment by PierreTurnbull** [comment]
It doesn't work for me too.

However it has nothing to do with the canberra issue. You should be able to solve the latter by installing some versions of it that you don't have. You should find all you need [here](https://askubuntu.com/questions/342202/failed-to-load-module-canberra-gtk-module-but-already-installed).

**Comment by HattinGokbori87** [comment]
f.lux doesn't work for most 18.04 users. Used to work till 17.10. The last time I tried to run it on 18.04, it showed a message saying it only supports probably 8 and 10 bit display. Use Redshift from official repository(sudo apt install redshift-gtk) and create the configuration file as described [here](http://jonls.dk/redshift/).

**Comment by mcoimbra** [comment]
Has there been any development regarding f.lux on Ubuntu 18.04?
I can start it but there is no panel icon nor interface for it.

**Comment by DimitrisPr** [comment]
Ubuntu 18.04.1 LTS here. It doens't work either. Will try to contribute ASAP.

**Comment by mcoimbra** [comment]
@DimitrisPr do you have any idea what the issue might be?
Caused by some gnome compatibility?
I ask because other programs such as Dropbox were affected as well.

**Comment by DimitrisPr** [comment]
xflux works only with python 2, but latest ubuntu update has only python 3 installed by default. Thi is probably the reason.

**Comment by cooperka** [comment]
fluxgui definitely worked for me on a fresh install of Ubuntu 18.04.1 LTS a couple weeks ago, but after installing Nvidia drivers and messing with Python configs and other things, it no longer works. I'm not sure what broke it but it **did** work on Ubuntu 18.04.1 LTS originally; screen turned red at sunset but now it just stays blue.

**Comment by cooperka** [comment]
And @ahmed-elsayed2017 to fix your `canberra-gtk-module` warning (doesn't fix xflux, but does make the warning go away):

```bash
sudo apt install libcanberra-gtk-module
```

**Comment by ntc2** [comment]
@anebz it depends on why it isn't working for you. If it's not working because of #27, then no, there is no plan to fix that. The `xflux` binary that actually changes the screen color is closed source, not maintained by us, and seemingly no longer maintained. If it's not working because of the "canberra gtk" problem, then try https://github.com/xflux-gui/fluxgui/issues/102#issuecomment-423400465.

**Comment by ahmed-elsayed2017** [comment]
OMG! I stopped using both Ubuntu and Flux from a few months. I've been using Manjaro and (Redshift with widget to control its settings).

**Comment by cooperka** [comment]
Do you mind keeping this issue open actually, @ahmed-elsayed2017? It's still a valid issue even if you don't personally need it anymore; it helps other people find it.

**Comment by ntc2** [comment]
I just closed this because
- `fluxgui` itself does work in Ubuntu 18.04 for me now with PR #112 merged, and I added the `ganberra-gtk-module` to the deps in the README, so I think only #27 remains.  **NOTE**:  `xflux` does not work for me on 18.04, so the screen color doesn't change, see the next point.
- as explained in #27, we can't fix that issue, because `xflux` is closed source. I think the long term solution is for users to abandon `fluxgui` and switch to `redshift-gtk`, or for `fluxgui` to add a backend that uses `redshift` to change the screen color. i'll create a separate issue for that ...

**Comment by ahmed-elsayed2017** [comment]
I use Redshift, and it has a widget to control its settings. You can find its widget if you are using KDE or Cinnamon.

**Comment by ntc2** [comment]
Yes, I'm using `redshift-gtk`, the `redshift` widget, on both my home and work computer now. Works great!

**Comment by lmingde** [comment]
I start flux, at begin the color change by flux, but quick return to the normal appearance which no use flux, what the problem it is? Anyone can help me?

**Comment by lmingde** [comment]
I start flux on Ubuntu 18.04, at begin the color change by flux, but quick return to the normal appearance which no use flux, what the problem it is? Anyone can help me?

**Comment by jmrf** [comment]
There's a `Night Light` setting in Ubuntu 18.10 (under Settings > Displays > Night Light) that I found it was in conflict with f.lux.
Launching f.lux from the command line would cause some flickering, I believe because of both f.lux and the Ubuntu setting trying to change the display color temperature.

Disabling the Ubuntu setting and running f.lux from the command line brought everything back to normal

**Comment by regulator-g** [comment]
Also recommend redshift, using it on 19.04 with no issues and I have a manual config file where i set the location, time and temp settings

**Comment by abhi1kush** [comment]
There's a Night Light setting in Ubuntu 18.10 (under Settings > Displays > Night Light) that I found it was in conflict with f.lux. Worked for me thanks jmrf

**Comment by mkstarr** [comment]
Bionic as well here. f.lux won't even start.
