### ISSUE TITLE
sudo apt-get install fluxgui after adding and updating repo(s) times out

### ISSUE THREAD

**Issue by mkstarr** [xflux-gui/fluxgui#138]
Well,  actually, it DOESN'T time out. It just kind of... sits there.

No feedback from the add-apt-repository command, no feedback from apt-get update, and, as I mentioned, just stalls on apt-get command.

**Comment by ntc2** [comment]
This sounds like an APT  or network configuration problem, and isn't really
in scope for this project. You might double check that there is a version
of fluxgui packaged for your system here:
https://launchpad.net/~nathan-renniewaldock/+archive/ubuntu/flux.  But if
there was no version of the package for your system then you should just
get an error, not that hanging behavior.

Also, due to Issue #27, fluxgui probably doesn't work on your system anyway
and you should just use redshift.
