### ISSUE TITLE
APT Distribution issue

### ISSUE THREAD

**Issue by k7faq** [xflux-gui/fluxgui#139]
pi@raspberrypi:~ $ sudo add-apt-repository ppa:nathan-renniewaldock/flux
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster

uname -a
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux

**Comment by etienne-chrp** [comment]
You are not running a distribution from the Ubuntu family but from the Debian family (Raspbian), this is not following the same release cycle. Hence the distribution *Raspbian/buster* could not be found by `add-apt-repository`

I would suggest than you add manually the PPA repo as explained <https://launchpad.net/~nathan-renniewaldock/+archive/ubuntu/flux>

You might need to add `sudo` in order to run the following
```bash
echo "
deb http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu eoan main 
deb-src http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu eoan main
" > /etc/apt/sources.list.d/fluxgui.repo
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4cdb129629a4b41a
apt update
apt install fluxgui
```
