### ISSUE TITLE
Feature Request: PyPi Release

### ISSUE THREAD

**Issue by jgarte** [xflux-gui/fluxgui#164]
Hi,

Can this program be released on PyPi?

**Comment by ntc2** [comment]
Maybe, is this something you're interested in setting up and maintaining?

**Comment by jgarte** [comment]
Hi,

I am mostly interested in maintaining the Guix package as I've been contributing to the Guix project:

https://github.com/guix-mirror/guix/commits?author=jgarte

Is the main reason for not putting xflux-gui on PyPI due to difficulty with non-Python dependency gathering or something else?

Would the person maintaining the PyPI release need to coordinate with the person who has access to the account for xflux-gui on PyPI?

**Comment by ntc2** [comment]
> I am mostly interested in maintaining the Guix package as I've been contributing to the Guix project:

> https://github.com/guix-mirror/guix/commits?author=jgarte

OK, then probably better for you to focus on a Guix package.

> Is the main reason for not putting xflux-gui on PyPI due to difficulty with non-Python dependency gathering or something else?

I don't know why xflux-gui is not on PyPi. I think of PyPi as place for hosting Python libraries, not applications written in Python, so naively I would assume that PyPi is not the right place to host xflux-gui. But I could be totally wrong about that, since I don't know much about PyPi, beyond it being the source for library deps installed by pip.

> Would the person maintaining the PyPI release need to coordinate with the person who has access to the account for xflux-gui on PyPI?

I don't understand this question. Are you saying there is already an "account for xflux-gui on PyPI"?

**Comment by jgarte** [comment]
> I don't understand this question. Are you saying there is already an "account for xflux-gui on PyPI"?

What I meant is that a person has to register for an account to have access to upload xflux-gui, as I understand it.

If I were to upload xflux-gui myself to PyPI then it would be under my own jgart account name which is probably not what the xflux-gui developers want.

Regarding apps on PyPi, there are apps on PyPi but we could just package xflux-gui for distros. Take for example, gajim, the xmpp client that is not on PyPi.

**Comment by ntc2** [comment]
> > I don't understand this question. Are you saying there is already an "account for xflux-gui on PyPI"?
> 
> What I meant is that a person has to register for an account to have access to upload xflux-gui, as I understand it.
> 
> If I were to upload xflux-gui myself to PyPI then it would be under my own jgart account name which is probably not what the xflux-gui developers want.

Since you would be maintaining this, uploading it to your account is fine. But let me emphasize again, the maintainers are not interested in being involved with maintaining xflux-gui on PyPI.

> Regarding apps on PyPi, there are apps on PyPi but we could just package xflux-gui for distros. Take for example, gajim, the xmpp client that is not on PyPi.

Your example is an app that is *not* on PyPi? Sure, I assume most apps are not on PyPi. An example of an app that is on PyPi would be more relevant/useful I think. But yes, I think just packaging xflux-gui for distros -- the current state of affairs -- makes more sense, since xflux-gui has various dependencies that are not themselves on PyPi.

**Comment by ntc2** [comment]
Zooming out a bit, what would probably be much more useful than a PyPi release would be to get the [Ubuntu PPA](https://launchpad.net/~nathan-renniewaldock/+archive/ubuntu/flux) updated with a fluxgui 2.0 release, by contacting the developer. Or creating a Fedora package.
