### ISSUE TITLE
Ubuntu 17.04 f.lux color temp doesn't change

### ISSUE THREAD

**Issue by azaa13** [xflux-gui/fluxgui#78]
I just upgraded ubuntu system from 16.10 to 17.04 then it f.lux didn't work. on 16.10 
f.lux works compelely fine but after ugrade color temp didnt change. Then uninstalled flux again installed. Installation process was fine, no error but after installation color temp doesn't change. 
Tried preview on flux but no response and crashed. 

Thanks!

**Comment by ntc2** [comment]
How does it "crash"? Did you check that you're not experiencing Issue #27?

**Comment by aleesoltani** [comment]
hey, I'm having troubles with fluxgui on ubuntu 17.04 too. it doesn't crash, it just doesn't change the color of the screen. nothing happens when I run it or press preview. the only thing that i thought could help you find the bug is that when I click on preview it just hangs up for like 5-10 seconds like the application is processing something or in some kind of a loop and then it comes back again like nothing's happened.
if u need further info message or email me. thanks btw for the app. worked great on windows.

**Comment by ntc2** [comment]
@aleesoltani Did you check that you're not experiencing Issue #27?

**Comment by aleesoltani** [comment]
I have used flux on this laptop on an older linux and also on windows and it worked ok! So I don’t think that’s the issue. But I’ll check that issue tomorrow and report what happens ;)

**Comment by aleesoltani** [comment]
@ntc2 Sorry for my late reply, it seems like my issue is #27 actually. But it's strange because I've been using Flux on this laptop on windows before and it worked great, but now I have completely migrated to linux. But redshift works for me, thanks anyway!

**Comment by ntc2** [comment]
Thanks for checking and following up. Yeah, unfortunately I have no idea how `xflux` works or why it would break on Linux kernel or video driver upgrades, but it seems that it does. Glad to hear Redshift is working for you.

**Comment by monsieurjean** [comment]
I just installed f.lux today. and I'm running it on my 	Ubuntu 16.04.3 LTS
I set my latitude and longitude properly, but nothing happens, even though I changed many times the night time colour temperature and clicked preview. But still. no results. nothing happens at all
I see no change in the colour temperature of the screen!
